const clips=[
['08','comparison','sf'],['10','comparison','cf'],['01','comparison','sf'],['02','comparison','sf'],['03','comparison','sf'],['04','comparison','sf'],['05','comparison','sf'],['06','comparison','sf'],['07','comparison','sf'],['09','comparison','cf'],['11','comparison','cf'],['12','comparison','cf'],['13','comparison','cf'],['14','comparison','cf'],['15','comparison','cf'],['16','comparison','sf'],['17','comparison','sf'],['18','comparison','sf'],['19','comparison','sf'],['20','comparison','sf']
];
const modelNames={sf:'Self Forcing',cf:'Causal Forcing'};
const video=document.querySelector('#comparison');let filter='all',selected='08';
const visibleClips=()=>clips.filter(c=>filter==='all'||c[2]===filter);
function choose(id,play=false){const c=clips.find(x=>x[0]===id);selected=id;video.pause();video.src=`assets/videos-web/${id}.mp4?v=web-v1`;video.poster=`assets/posters/${id}.jpg?v=fullres`;video.setAttribute('aria-label',`Six-method comparison, ${modelNames[c[2]]}`);video.load();document.querySelector('#clip-model').textContent=modelNames[c[2]];document.querySelectorAll('.scene').forEach(b=>{const s=b.dataset.id===id;b.classList.toggle('selected',s);b.setAttribute('aria-pressed',s)});if(play)video.play().catch(()=>{});}
function renderClips(){const grid=document.querySelector('#scene-grid');grid.replaceChildren(...visibleClips().map(([id,title,model])=>{const b=document.createElement('button');b.className='scene'+(selected===id?' selected':'');b.dataset.id=id;b.setAttribute('aria-label',`Play comparison, ${modelNames[model]}`);b.setAttribute('aria-pressed',selected===id);b.innerHTML=`<div class="scene-image"><img src="assets/thumbnails/${id}.jpg?v=fullres" alt="" loading="lazy"></div>`;b.addEventListener('click',()=>choose(id,true));return b}));}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});if(!visibleClips().some(c=>c[0]===selected))choose(visibleClips()[0][0]);renderClips()}));
function move(direction){const set=visibleClips();const index=set.findIndex(c=>c[0]===selected);choose(set[(index+direction+set.length)%set.length][0],true)}document.querySelector('#prev').onclick=()=>move(-1);document.querySelector('#next').onclick=()=>move(1);renderClips();
const data={333:[['Original 4 steps',32.93,'1.00',82.55],['Original 2 steps',16.53,'1.99',82.35],['TeaCache',17.50,'1.88',81.47],['TaylorSeer',18.67,'1.76',80.69],['MotionCache',19.12,'1.72',81.56],['DisCa',17.32,'1.90',82.12],['TGuide (Ours)',17.46,'1.89',82.71]],81:[['Original 4 steps',6.53,'1.00',84.28],['Original 2 steps',3.48,'1.88',84.09],['TeaCache',3.83,'1.71',83.91],['TaylorSeer',3.78,'1.73',83.68],['MotionCache',3.96,'1.65',83.97],['DisCa',3.59,'1.82',83.86],['TGuide (Ours)',3.62,'1.80',84.23]]};
function renderResults(length){const rows=data[length];document.querySelector('#results-body').innerHTML=rows.map((r,i)=>`<tr${i===6?' class="ours-row"':''}><td>${r[0]}</td><td>${r[1].toFixed(2)} s</td><td>${r[2]}×</td><td>${r[3].toFixed(2)}</td></tr>`).join('');const original=rows[0],ours=rows[6];document.querySelector('#result-speed').innerHTML=`${ours[2]}<span>×</span>`;document.querySelector('#original-latency').textContent=original[1].toFixed(2)+' s';document.querySelector('#ours-latency').textContent=ours[1].toFixed(2)+' s';document.querySelector('#latency-bar').style.width=ours[1]/original[1]*100+'%';document.querySelector('#quality-note').innerHTML=`<b>${ours[3].toFixed(2)}</b> VBench total score<br><span>${length==='81'?'0.05 points below the original model':'+0.16 points over the original model'}</span>`;}
document.querySelectorAll('[data-length]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-length]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});renderResults(b.dataset.length)}));renderResults('333');
const heroIds=[['01','02','20'],['06','16','09'],['18','04','01'],['20','09','02']];const wall=document.querySelector('#wall');const reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches;const motion=document.querySelector('#motion');
heroIds.forEach(ids=>{const column=document.createElement('div');column.className='wall-column';ids.forEach(id=>{const v=document.createElement('video');v.className='wall-tile';v.muted=true;v.loop=true;v.playsInline=true;v.preload='none';v.poster=`assets/hero/${id}.jpg?v=fullres`;v.src=`assets/hero-web/${id}.mp4?v=web-v1`;column.append(v)});wall.append(column)});
function updateMotion(inView=true){document.querySelectorAll('.wall-tile').forEach(v=>{if(paused||!inView||document.hidden)v.pause();else v.play().catch(()=>{})});motion.textContent=paused?'Play background':'Pause background';motion.setAttribute('aria-pressed',paused)}
motion.onclick=()=>{paused=!paused;updateMotion()};let heroVisible=true;new IntersectionObserver(([entry])=>{heroVisible=entry.isIntersecting;updateMotion(heroVisible)},{threshold:0}).observe(document.querySelector('.hero'));document.addEventListener('visibilitychange',()=>updateMotion(heroVisible));new IntersectionObserver(([entry])=>{if(!entry.isIntersecting)video.pause()},{threshold:0}).observe(video);reduced.addEventListener('change',e=>{paused=e.matches;updateMotion(heroVisible)});updateMotion();

// Leave unpublished arXiv entries in place without navigating to an empty URL.
document.querySelectorAll('[data-arxiv-link]').forEach(link=>link.addEventListener('click',event=>{if(!link.getAttribute('href').trim())event.preventDefault()}));
